changed the tree structure of the app/ useInput, etc.
BelohvostovAlex/webpack pull request #2
Opened 2022-05-16 07:56 UTC by BelohvostovAlex

2022-05-16 12:25 UTC, igorTT requested changes

2022-05-16 12:25 UTC, igorTT commented on src/components/Button/Button.tsx
> +  onSubmit,
Replace with `onClick` it can be cancel button

2022-05-16 12:25 UTC, igorTT commented on src/components/Button/Button.tsx
> +import './formButton.scss'
Use one type of quotes. Prefer single-quote

2022-05-16 12:25 UTC, igorTT commented on src/components/Button/ButtonContainer.tsx
> +  onSub,
Don't save the place on the screen. Use readable names. onSub- on subscribe?

2022-05-16 12:25 UTC, igorTT commented on src/components/Button/ButtonContainer.tsx
> +};
Use a simple button. Don't try to spread the logic. I don't see the reason to preventDefault. If you need to do it- it'll be easier to do it on some upper level

2022-05-16 12:25 UTC, igorTT commented on src/components/Form/Form.tsx
> +import { ButtonContainer } from "../Button";
Replace with a simple button

2022-05-16 12:25 UTC, igorTT commented on src/components/Form/FormContainer.tsx
> +  const password = useInput("");
Replace with
```javascript
  const [username, setUserame] = useInput();
  const [password, setPassword] = useInput();

2022-05-16 12:25 UTC, igorTT commented on src/components/Form/FormContainer.tsx
> +      password.setValue("");
Pass an empty parameter to the handler. It'll be more common logic.

2022-05-16 12:25 UTC, igorTT commented on src/hooks/useInput.tsx
> +  return {value, setValue, handleValue}
You don't need to use setValue on the lower level

2022-05-16 13:02 UTC, BelohvostovAlex commented on src/components/Button/Button.tsx
> +import './formButton.scss'
done

2022-05-16 13:52 UTC, BelohvostovAlex commented on src/components/Button/ButtonContainer.tsx
> +};
done

2022-05-16 14:38 UTC, BelohvostovAlex commented on src/components/Form/FormContainer.tsx
> +  const password = useInput("");
done

2022-05-17 04:30 UTC, igorTT approved these changes

2022-05-17 04:57 UTC, merged